config/routes.rb
Fstmind::Application.routes.draw do
  resources :comments
  
  resources :posts do
    resources :comments
  end

  resources :posts
  root 'home#index'
  devise_for :users
  resources :industries
  
  devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    get "home/index"
    get "static_page/posts"
    get "static_page/blog"
    get "static_page/questions"
    get "post/index"
    get "post/show"
end

app/models/industry.rb
class Industry < ActiveRecord::Base
  has_many :users
end

app/controllers/industries_controller.rb
class IndustriesController < ApplicationController
  before_action :set_Industry, only: [:show, :edit, :update, :destroy]

  def index
    @industries = Industry.all
  end

  def show
    @industry = Industry.find(params[:id])
  end

  def new
    @industry = Industry.new
  end

  def edit
  end

  def create
    @industry = Industry.new(industry_params)

    respond_to do |format|
      if @industry.save
        format.html { redirect_to @industry, notice: 'Industry was successfully created.' }
        format.json { render action: 'show', status: :created, location: @industry }
      else
        format.html { render action: 'new' }
        format.json { render json: @industry.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @industry.update(industry_params)
        format.html { redirect_to @industry, notice: 'Industry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @industry.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @industry.destroy
    respond_to do |format|
      format.html { redirect_to industries_url }
      format.json { head :no_content }
    end
  end

  private
   
    def set_Industry
      @industry = Industry.find(params[:id])
    end

   
    def industry_params
      params.require(:industry).permit(:name, :status)
    end
end

app/helpers/industries_helper.rb
module IndustriesHelper
end

app/views/industries/_form.html.erb
<%= form_for(@industry) do |f| %>
  <% if @industry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@industry.errors.count, "error") %> prohibited this industry from being saved:</h2>

      <ul>
      <% @industry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/industries/edit.html.erb
<h1>Editing industry</h1>

<%= render 'form' %>

<%= link_to 'Show', @industry %> |
<%= link_to 'Back', industries_path %>

app/views/industries/index.html.erb
<h1>Listing industries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @industries.each do |industry| %>
      <tr>
        <td><%= industry.name %></td>
        <td><%= industry.status %></td>
        <td><%= link_to 'Show', industry %></td>
        <td><%= link_to 'Edit', edit_industry_path(industry) %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Industry', new_industry_path %>

app/views/industries/new.html.erb
<h1>New industry</h1>

<%= render 'form' %>

<%= link_to 'Back', industries_path %>

app/views/industries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @industry.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @industry.status %>
</p>

<%= link_to 'Edit', edit_industry_path(@industry) %> |
<%= link_to 'Back', industries_path %>